// <auto-generated />
using System;
using Medgrupo.Siscolar.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medgrupo.Siscolar.Infra.Migrations
{
    [DbContext(typeof(SiscolarDbContext))]
    [Migration("20200627181507_OneSchoolWithManySchoolClass")]
    partial class OneSchoolWithManySchoolClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSchoolClass")
                        .HasColumnType("int");

                    b.Property<int>("MaxSchoolStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(160);

                    b.Property<string>("SchoolPrincipal")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = new Guid("950c9298-737f-4562-ae74-adf53ef099ec"),
                            CreateDate = new DateTime(2020, 6, 27, 15, 15, 6, 541, DateTimeKind.Local).AddTicks(3214),
                            LastUpdateDate = new DateTime(2020, 6, 27, 15, 15, 6, 541, DateTimeKind.Local).AddTicks(3214),
                            MaxSchoolClass = 10,
                            MaxSchoolStudents = 100,
                            Name = "Escola João de Barro",
                            SchoolPrincipal = "Sr. Roggani"
                        },
                        new
                        {
                            Id = new Guid("8b005216-1b99-43f0-af3d-e1a01fbe18e4"),
                            CreateDate = new DateTime(2020, 6, 27, 15, 15, 6, 550, DateTimeKind.Local).AddTicks(6723),
                            LastUpdateDate = new DateTime(2020, 6, 27, 15, 15, 6, 550, DateTimeKind.Local).AddTicks(6723),
                            MaxSchoolClass = 15,
                            MaxSchoolStudents = 150,
                            Name = "Escola Estadual Paulo Freire",
                            SchoolPrincipal = "Sr. Afonso"
                        },
                        new
                        {
                            Id = new Guid("8a013b0e-eaaa-4349-acbf-e067270cf87b"),
                            CreateDate = new DateTime(2020, 6, 27, 15, 15, 6, 550, DateTimeKind.Local).AddTicks(6824),
                            LastUpdateDate = new DateTime(2020, 6, 27, 15, 15, 6, 550, DateTimeKind.Local).AddTicks(6824),
                            MaxSchoolClass = 11,
                            MaxSchoolStudents = 110,
                            Name = "Escola Federal Pedro Ernesto",
                            SchoolPrincipal = "Sr. José Aldo"
                        });
                });

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.SchoolClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(160);

                    b.Property<string>("SchoolClassCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a7572b4-a4a5-4116-bd29-4b34fe6d6746"),
                            CreateDate = new DateTime(2020, 6, 27, 15, 15, 6, 565, DateTimeKind.Local).AddTicks(1965),
                            LastUpdateDate = new DateTime(2020, 6, 27, 15, 15, 6, 565, DateTimeKind.Local).AddTicks(1965),
                            Name = "Turma da 5ª Série",
                            SchoolClassCode = "M20A4A5965",
                            SchoolId = new Guid("950c9298-737f-4562-ae74-adf53ef099ec"),
                            SchoolYear = 2020,
                            Shift = "Matutino"
                        },
                        new
                        {
                            Id = new Guid("bc6f1f78-6e9b-4da3-8588-0c337fb3525a"),
                            CreateDate = new DateTime(2020, 6, 27, 15, 15, 6, 567, DateTimeKind.Local).AddTicks(5883),
                            LastUpdateDate = new DateTime(2020, 6, 27, 15, 15, 6, 567, DateTimeKind.Local).AddTicks(5883),
                            Name = "Turma da 7ª Série",
                            SchoolClassCode = "V206E9B883",
                            SchoolId = new Guid("8b005216-1b99-43f0-af3d-e1a01fbe18e4"),
                            SchoolYear = 2020,
                            Shift = "Vespertino"
                        },
                        new
                        {
                            Id = new Guid("f3bb23a2-b65d-4ce7-ad72-d6d0db9710b5"),
                            CreateDate = new DateTime(2020, 6, 27, 15, 15, 6, 567, DateTimeKind.Local).AddTicks(6187),
                            LastUpdateDate = new DateTime(2020, 6, 27, 15, 15, 6, 567, DateTimeKind.Local).AddTicks(6187),
                            Name = "Turma da 8ª Série",
                            SchoolClassCode = "N20B65D187",
                            SchoolId = new Guid("8a013b0e-eaaa-4349-acbf-e067270cf87b"),
                            SchoolYear = 2020,
                            Shift = "Noturno"
                        });
                });

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.SchoolClass", b =>
                {
                    b.HasOne("Medgrupo.Siscolar.Domain.Entities.School", "School")
                        .WithMany("SchoolClasses")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
