// <auto-generated />
using System;
using Medgrupo.Siscolar.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medgrupo.Siscolar.Infra.Migrations
{
    [DbContext(typeof(SiscolarDbContext))]
    [Migration("20200627062808_SchoolClassEntity")]
    partial class SchoolClassEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSchoolClass")
                        .HasColumnType("int");

                    b.Property<int>("MaxSchoolStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(160);

                    b.Property<string>("SchoolPrincipal")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82d921ac-7a07-4e46-9101-6bd2ccb2088e"),
                            CreateDate = new DateTime(2020, 6, 27, 3, 28, 7, 159, DateTimeKind.Local).AddTicks(4267),
                            LastUpdateDate = new DateTime(2020, 6, 27, 3, 28, 7, 159, DateTimeKind.Local).AddTicks(4267),
                            MaxSchoolClass = 10,
                            MaxSchoolStudents = 100,
                            Name = "Escola João de Barro",
                            SchoolPrincipal = "Sr. Roggani"
                        },
                        new
                        {
                            Id = new Guid("d8a61f26-98eb-47ab-98d4-c16246159718"),
                            CreateDate = new DateTime(2020, 6, 27, 3, 28, 7, 169, DateTimeKind.Local).AddTicks(8581),
                            LastUpdateDate = new DateTime(2020, 6, 27, 3, 28, 7, 169, DateTimeKind.Local).AddTicks(8581),
                            MaxSchoolClass = 15,
                            MaxSchoolStudents = 150,
                            Name = "Escola Estadual Paulo Freire",
                            SchoolPrincipal = "Sr. Afonso"
                        },
                        new
                        {
                            Id = new Guid("6e6056c0-fbc6-4201-96fb-2cc29c47f478"),
                            CreateDate = new DateTime(2020, 6, 27, 3, 28, 7, 169, DateTimeKind.Local).AddTicks(8680),
                            LastUpdateDate = new DateTime(2020, 6, 27, 3, 28, 7, 169, DateTimeKind.Local).AddTicks(8680),
                            MaxSchoolClass = 11,
                            MaxSchoolStudents = 110,
                            Name = "Escola Federal Pedro Ernesto",
                            SchoolPrincipal = "Sr. José Aldo"
                        });
                });

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.SchoolClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(160);

                    b.Property<string>("SchoolClassCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SchoolClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b30e1ac-d993-48f7-b8bf-77ca88c289b7"),
                            CreateDate = new DateTime(2020, 6, 27, 3, 28, 7, 176, DateTimeKind.Local).AddTicks(5402),
                            LastUpdateDate = new DateTime(2020, 6, 27, 3, 28, 7, 176, DateTimeKind.Local).AddTicks(5402),
                            Name = "Turma da 5ª Série",
                            SchoolClassCode = "d993M205402",
                            SchoolYear = 2020,
                            Shift = "Matutino"
                        },
                        new
                        {
                            Id = new Guid("d99ec33e-1745-482e-8344-1435fe83fced"),
                            CreateDate = new DateTime(2020, 6, 27, 3, 28, 7, 178, DateTimeKind.Local).AddTicks(2093),
                            LastUpdateDate = new DateTime(2020, 6, 27, 3, 28, 7, 178, DateTimeKind.Local).AddTicks(2093),
                            Name = "Turma da 7ª Série",
                            SchoolClassCode = "1745V202093",
                            SchoolYear = 2020,
                            Shift = "Vespertino"
                        },
                        new
                        {
                            Id = new Guid("2dcc54e4-9e55-4bdf-baf0-634f9ba70780"),
                            CreateDate = new DateTime(2020, 6, 27, 3, 28, 7, 178, DateTimeKind.Local).AddTicks(2304),
                            LastUpdateDate = new DateTime(2020, 6, 27, 3, 28, 7, 178, DateTimeKind.Local).AddTicks(2304),
                            Name = "Turma da 8ª Série",
                            SchoolClassCode = "9e55N202304",
                            SchoolYear = 2020,
                            Shift = "Noturno"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
