// <auto-generated />
using System;
using Medgrupo.Siscolar.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medgrupo.Siscolar.Infra.Migrations
{
    [DbContext(typeof(SiscolarDbContext))]
    partial class SiscolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSchoolClass")
                        .HasColumnType("int");

                    b.Property<int>("MaxSchoolStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(160);

                    b.Property<string>("SchoolPrincipal")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = new Guid("937fc52c-5667-4f14-a662-cd87ff6213cc"),
                            CreateDate = new DateTime(2020, 6, 26, 21, 10, 3, 445, DateTimeKind.Local).AddTicks(1479),
                            LastUpdateDate = new DateTime(2020, 6, 26, 21, 10, 3, 445, DateTimeKind.Local).AddTicks(1479),
                            MaxSchoolClass = 10,
                            MaxSchoolStudents = 100,
                            Name = "Escola João de Barro",
                            SchoolPrincipal = "Sr. Roggani"
                        },
                        new
                        {
                            Id = new Guid("b52600f7-cb8c-4d9f-ab32-b57a091cf5b9"),
                            CreateDate = new DateTime(2020, 6, 26, 21, 10, 3, 453, DateTimeKind.Local).AddTicks(1532),
                            LastUpdateDate = new DateTime(2020, 6, 26, 21, 10, 3, 453, DateTimeKind.Local).AddTicks(1532),
                            MaxSchoolClass = 15,
                            MaxSchoolStudents = 150,
                            Name = "Escola Estadual Paulo Freire",
                            SchoolPrincipal = "Sr. Afonso"
                        },
                        new
                        {
                            Id = new Guid("6d1e0197-90af-4985-a5fe-828f28cfb06d"),
                            CreateDate = new DateTime(2020, 6, 26, 21, 10, 3, 453, DateTimeKind.Local).AddTicks(1609),
                            LastUpdateDate = new DateTime(2020, 6, 26, 21, 10, 3, 453, DateTimeKind.Local).AddTicks(1609),
                            MaxSchoolClass = 11,
                            MaxSchoolStudents = 110,
                            Name = "Escola Federal Pedro Ernesto",
                            SchoolPrincipal = "Sr. José Aldo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
