// <auto-generated />
using System;
using Medgrupo.Siscolar.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medgrupo.Siscolar.Api.Migrations
{
    [DbContext(typeof(SiscolarDbContext))]
    [Migration("20200626060805_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medgrupo.Siscolar.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxSchoolClass")
                        .HasColumnType("int");

                    b.Property<int>("MaxSchoolStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(160);

                    b.HasKey("Id");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d4f653f-adfd-4b89-9811-20def628c407"),
                            MaxSchoolClass = 0,
                            MaxSchoolStudents = 0,
                            Name = "Escola João de Barro"
                        },
                        new
                        {
                            Id = new Guid("c936f200-39db-4411-944b-03ff307933db"),
                            MaxSchoolClass = 0,
                            MaxSchoolStudents = 0,
                            Name = "Escola Estadual Paulo Freire"
                        },
                        new
                        {
                            Id = new Guid("e14a3b32-2919-45b7-8df1-8fe4caa64104"),
                            MaxSchoolClass = 0,
                            MaxSchoolStudents = 0,
                            Name = "Escola Federal Pedro Ernesto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
